# Generated by Django 4.2.4 on 2024-07-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='deliveryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
