# Generated by Django 4.2.4 on 2024-07-20 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_alter_collection_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='customerName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 13, 21, 16, 303228)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
