# Generated by Django 4.2.4 on 2024-07-20 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_collection_address_collection_customername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='status',
            new_name='collectionStatus',
        ),
        migrations.AlterField(
            model_name='collection',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 14, 36, 39, 740758)),
        ),
    ]
