# Generated by Django 4.2.4 on 2024-07-20 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_rename_status_collection_collectionstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collectionStatus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='collection',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 15, 51, 43, 927722)),
        ),
    ]
