# Generated by Django 4.2.4 on 2024-07-20 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_rename_collectionstatus_collection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collectionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 16, 31, 38, 627141)),
        ),
    ]
